### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by IAmSilK** [openmod/openmod-docs#14]
Each link which ends in `.md` in the `development-guide` directory is broken. All links ending in `.md` which aren't in this directory work though.

Alongside this, `translations.md` needs to be changed to the new `localization.md` doc file.

I'd create a PR and just change these links to end with a `/` rather than `.md`, but I suspect there's an underlying issue with the compilation of the docs as `.md` endings work outside of this directory.

**Comment by Trojaner** [comment]
.md is not a requirement so it should work without it too

**Comment by IAmSilK** [comment]
Should I create a PR replacing .md on the broken links?

**Comment by Trojaner** [comment]
Yes, that would be great
